### PR TITLE
Development

### PR DESCRIPTION
**Pull request by JamesOkunlade**

### CODE REVIEW

**Comment by JamesOkunlade** [comment]
Hello @rvvergara  Thanks for the prompt review.

I have fixed the node_modules that was pushed to the development branch mistakenly. Also I tried to check the other two issues you mentioned and here are screenshots of my own console when I tried to create my own `first app`.

image

and this 
image

We're not sure what could have caused the errors on your own side. Please ensure you `npm run build` after installing and we would appreciate if you can hint us on where to check to fix this.

Thanks.

**Comment by JamesOkunlade** [comment]
It would be impossible for us to debug cos we'll need to click on the uncaught error to see where it's coming from. If you could possibly do that for us and send a screenshot, please. :pray:

**Comment by rvvergara** [comment]
Error when initially loading the app:

image

Error when trying to create a new project:

image


I already suggested to you a way to recreate the problem - run `localStorage.clear()` on your console before reloading the app. I am having this issue, I suspect, because I don't have a pre-loaded project in my localstorage.

**Comment by rvvergara** [comment]
## AWESOME WORK GUYS!!! :medal_sports: 

Ok thanks for fixing the issue and now I can use the app smoothly!

Nice transitions and features! I like the "SHOW DETAILS" part which only displays the task related buttons when necessary - keeps the interface clean.

As for the codebase. I don't have anything major to comment on. All is well. 

So this is a 

# :+1:

**Comment by AdnanAfsari** [comment]
Thanks

**Pull request merged**
